---
kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: if-not-exists
  image: docker:19.03.12-dind
  commands:
  - n=0; while [ "$n" -lt 60 ] && [ ! -e /var/run/docker.sock ]; do n=$(( n + 1 )); sleep 1; done
  - docker build -t acp-multipage-example-app:$${DRONE_COMMIT_SHA} . --no-cache
  volumes:
  - name: dockersock
    path: /var/run
  when:
    event:
    - push
    - tag

- name: scan-image
  image: docker.digital.homeoffice.gov.uk/acp-anchore-submission:latest
  environment:
    IMAGE_NAME: acp-multipage-example-app:${DRONE_COMMIT_SHA}
    SERVICE_URL: http://anchore-submission-server:10080
    WHITELIST: CVE-2008-4318
  volumes:
  - name: dockersock
    path: /var/run
  when:
    event:
    - push
    - tag

- name: push_artifactory_latest
  pull: if-not-exists
  image: docker:19.03.12-dind
  commands:
  - docker login -u="drone-acp-multipage-example-app" -p=$${ARTIFACTORY_PASSWORD} docker.digital.homeoffice.gov.uk
  - docker tag acp-multipage-example-app:$${DRONE_COMMIT_SHA} docker.digital.homeoffice.gov.uk/acp-multipage-example-app:latest
  - docker tag acp-multipage-example-app:$${DRONE_COMMIT_SHA} docker.digital.homeoffice.gov.uk/acp-multipage-example-app:$${DRONE_COMMIT_SHA}
  - docker push docker.digital.homeoffice.gov.uk/acp-multipage-example-app:latest
  - docker push docker.digital.homeoffice.gov.uk/acp-multipage-example-app:$${DRONE_COMMIT_SHA}
  environment:
    ARTIFACTORY_PASSWORD:
      from_secret: artifactory_password
  volumes:
  - name: dockersock
    path: /var/run
  when:
    branch:
    - master
    event:
    - push

- name: push_artifactory_tag
  pull: if-not-exists
  image: docker:19.03.12-dind
  commands:
  - docker login -u="drone-acp-multipage-example-app" -p=$${ARTIFACTORY_PASSWORD} docker.digital.homeoffice.gov.uk
  - docker tag acp-multipage-example-app:$${DRONE_COMMIT_SHA} docker.digital.homeoffice.gov.uk/acp-multipage-example-app:$${DRONE_TAG}
  - docker push docker.digital.homeoffice.gov.uk/acp-multipage-example-app:$${DRONE_TAG}
  environment:
    ARTIFACTORY_PASSWORD:
      from_secret: artifactory_password
  volumes:
    - name: dockersock
      path: /var/run
  when:
    event:
    - tag

services:
- name: docker
  image: docker:19.03.12-dind
  volumes:
  - name: dockersock
    path: /var/run

- name: anchore-submission-server
  image: docker.digital.homeoffice.gov.uk/acp-anchore-submission:latest
  commands:
    - /anchore-submission server
  environment:
    ANCHORE_URL: "acp-anchore.acp.homeoffice.gov.uk"
    REGISTRY_URL: "acp-ephemeral-registry.acp.homeoffice.gov.uk"
  volumes:
  - name: dockersock
    path: /var/run

volumes:
- name: dockersock
  temp: {}
...