---
kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: if-not-exists
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  commands:
  # wait for docker service to be up before running docker build
  - /usr/local/bin/wait
  - docker build -t "acp-multipage-example-app:${DRONE_COMMIT_SHA}" . --no-cache
  when:
    event:
    - pull_request
    - tag

- name: trivy_sast
  pull: Always
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/trivy/client:latest
  resources:
    limits:
      cpu: 1000
      memory: 1024Mi
  environment:
    IMAGE_NAME: "acp-multipage-example-app:${DRONE_COMMIT_SHA}"
    IGNORE_UNFIXED: "true"
    FAIL_ON_DETECTION: "true"
  when:
    event:    
    - pull_request

- name: push_tag_to_ecr
  image: plugins/ecr
  pull: if-not-exists
  settings:
    registry: 340268328991.dkr.ecr.eu-west-2.amazonaws.com
    repo: acp/multipage-example-app
    tags:
    - "${DRONE_TAG}"  
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_access_key
    AWS_REGION: eu-west-2
  when:
    event: 
    - tag

- name: push_tag_to_artifactory
  pull: if-not-exists
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  commands:
  - docker login -u=$${ARTIFACTORY_USERNAME} -p=$${ARTIFACTORY_PASSWORD} docker.digital.homeoffice.gov.uk
  - docker tag acp-multipage-example-app:$${DRONE_COMMIT_SHA} docker.digital.homeoffice.gov.uk/acp-multipage-example-app:$${DRONE_TAG}
  - docker push docker.digital.homeoffice.gov.uk/acp-multipage-example-app:$${DRONE_TAG}
  environment:
    ARTIFACTORY_PASSWORD:
      from_secret: artifactory_password
    ARTIFACTORY_USERNAME:
      from_secret: artifactory_username
  when:
    event:
    - tag

services:
- name: docker
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind